---

- name: Check installed nodebrew
  shell: $SHELL -lc "which nodebrew"
  ignore_errors: true
  register: nodebrew_installed

- name: Install nodebrew
  shell: curl -L git.io/nodebrew | perl - setup
  when: nodebrew_installed|failed

- name: Check installed node.js
  shell: $SHELL -lc "which node"
  ignore_errors: true
  register: nodejs_installed

- name: Check installed node.js version
  shell: $SHELL -lc "nodebrew ls | grep v8.1.3"
  ignore_errors: true
  when: nodejs_installed|success
  register: nodejs_target_version_exist

- name: Install node.js
  shell: nodebrew install-binary v8.1.3
  when: (nodejs_installed|failed) or (nodejs_target_version_exist|failed)

- name: use nodejs 8.1.3
  shell: nodebrew use v8.1.3
