---

- name: Clone dotfiles
  git:
    repo: git@github.com:suttang/dotfiles.git
    dest: ~/workspace/dotfiles

- name: Create .zshrc symlink
  file:
    src: ~/workspace/dotfiles/.zshrc
    dest: ~/.zshrc
    state: link

- name: Create .hyper.js symlink
  file:
    src: ~/workspace/dotfiles/.hyper.js
    dest: ~/.hyper.js
    state: link

- name: Create .config symlink
  file:
    src: ~/workspace/dotfiles/.config
    dest: ~/.config
    state: link